#!/bin/sh
node -e "
const fs = require('fs');
const pkg = JSON.parse(fs.readFileSync('client/package.json', 'utf8'));
const [major, minor, patch] = pkg.version.split('.').map(Number);
pkg.version = \`\${major}.\${minor}.\${patch + 1}\`;
fs.writeFileSync('client/package.json', JSON.stringify(pkg, null, 2) + '\n');
console.log('Version bumped to ' + pkg.version);
"
git add client/package.json
